{% set name = "thatool" %}
{% set version = "1.1.4" %}


package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 31198d2a1aee1f6d333aa111d045012e0b6362822bdaba25129e663dab446266

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  
requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy
    - scipy
    - pandas
    - ele
    - lmfit
    - shapely 
    - natsort 
    - matplotlib-base
    

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    # - thatool
    # - thatool.io
    # - thatool.free_energy
    - thatool.model
    # - thatool.colvar

about:
  home: The package home page
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "This package contains several in-house codes to handle some specific tasks. This package is developed and maintained by @thangckt"
  doc_url: https://thangckt.github.io/thatool/


extra:
  recipe-maintainers:
    - thangckt
