{% set name = "thatool" %}
{% set version = "1.1.5" %}


package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 93a95dab7bf367fac0a55f78317ea7520879338130ac4c37e7be68d63add117b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  
requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - scipy
    - pandas
    - ele
    - shapely 
    - natsort 
    - matplotlib
    

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    # - thatool
    # - thatool.io
    # - thatool.free_energy
    - thatool.model
    # - thatool.colvar

about:
  home: The package home page
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "This package contains several in-house codes to handle some specific tasks. This package is developed and maintained by @thangckt"
  doc_url: https://thangckt.github.io/thatool/


extra:
  recipe-maintainers:
    - thangckt
